# Generated by Django 3.1.2 on 2020-10-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201012_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default-avatar-profile-image-vector-social-media-user-icon-potrait-182347582.jpg', upload_to='users/'),
        ),
    ]
