# Generated by Django 3.1.2 on 2020-10-13 17:59

from django.db import migrations
import requests, json
import decimal

def get_routes(apps, schema_editor):
    Route = apps.get_model("climbguide", "Route")
    # Current lat/long for Asheville, NC
    # Routes within 50 miles
    latitude = decimal.Decimal("35.5951")
    longitude = decimal.Decimal("-82.5515")
    maxDistance = 50
    maxResults = 500
    key = "200940496-5b219988912aeeaf56bcbcdc264eedab"
    json_routes = requests.get(f"https://www.mountainproject.com/data/get-routes-for-lat-lon?lat={latitude}&lon={longitude}&maxDistance={maxDistance}&maxResults={maxResults}&key={key}")
    routes = json_routes.json()
    for route in routes:
        if Route.objects.get(mountainproject_id__exact=route["id"]):
            continue
        else:
            Route.objects.create(
                mountainproject_id=route["id"],
                name=route["name"],
                route_type=route["type"],
                rating=route["rating"],
                mp_stars=route["stars"],
                pitches=route["pitches"],
                location=route["location"]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('climbguide', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_routes),
    ]
