# Generated by Django 3.1.2 on 2020-10-14 19:45

from django.db import migrations, models
import requests, json
import decimal

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),)
environ.Env.read_env()

def get_routes(apps, schema_editor):
    Route = apps.get_model("climbguide", "Route")
    # Current lat/long for Asheville, NC
    # Routes within 50 miles
    latitude = decimal.Decimal("35.5951")
    longitude = decimal.Decimal("-82.5515")
    maxDistance = 50
    maxResults = 500
    key = env("MOUNTAIN_PROJECT_KEY")
    routes_data = requests.get(f"https://www.mountainproject.com/data/get-routes-for-lat-lon?lat={latitude}&lon={longitude}&maxDistance={maxDistance}&maxResults={maxResults}&key={key}")
    routes = routes_data.json()
    for route in routes["routes"]:
            Route.objects.create(
                mountainproject_id=route["id"],
                name=route["name"],
                route_type=route["type"],
                rating=route["rating"],
                mp_stars=route["stars"],
                pitches=route["pitches"],
                location=route["location"],
                latitude=route["latitude"],
                longitude=route["longitude"],
            )

class Migration(migrations.Migration):

    dependencies = [
        ('climbguide', '0002_auto_20201013_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(get_routes),
    ]
