# Generated by Django 3.1.2 on 2020-10-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climbguide', '0005_auto_20201015_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointofinterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('public', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('HG', 'Hangout Spot'), ('PG', 'Parking'), ('TH', 'Trailhead'), ('VP', 'Viewpoint')], default='HG', max_length=2)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointsofinterest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='point_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='climbguide.pointofinterest'),
        ),
        migrations.AddField(
            model_name='photo',
            name='point_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='climbguide.pointofinterest'),
        ),
    ]
