# Generated by Django 3.1.2 on 2020-10-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbguide', '0006_auto_20201018_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='description',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='information',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
