# Generated by Django 3.1.2 on 2020-10-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbguide', '0007_auto_20201018_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrip',
            name='points_of_interest',
            field=models.ManyToManyField(blank=True, related_name='daytrips', to='climbguide.Pointofinterest'),
        ),
    ]
