# Generated by Django 3.1.2 on 2020-10-21 00:45

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('climbguide', '0009_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointofinterest', to='climbguide.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (-80.793457, 35.782169), 'style': 'mapbox://styles/mapbox/streets-v11', 'zoom': 5}),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
